name: Run Postman Collection

on: [push]

jobs:
  run-postman-collection:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          npm install -g newman-reporter-htmlextra
          echo "Check dependencies version"
          npx newman --version
          npx newman-reporter-htmlextra --version

      - name: Run Postman collection
        run: |
          echo "Creating report directory"
          mkdir -p ./newman
          npx newman run ./postman/Ardilla_Retail_Withdrawal_Requests_web.postman_collection.json -r cli,htmlextra --reporter-htmlextra-export ./newman/results.html

      - name: Check if results.html exists
        run: ls -l ./newman

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-results
          path: ./newman/results.html
